# Default values for k8s-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: gcr.io/fabijanbajo/k8s-webhook
  tag: "0.1.0"
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
  - host: devops.fabijanbajo.com
    paths:
    - /hooks/github-webhook
    - /hooks/gitlab-webhook
  tls:
  - secretName: fabijanbajo-tls-secret
    hosts:
    - devops.fabijanbajo.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

webhook:
  customVolumeMounts: []
  # webhook configuration: https://github.com/adnanh/webhook
  # - name: mywebhook-configmap
  #   mountPath: /emptydir-volume/mywebhook.yaml
  #   subPath: mywebhook.yaml
  scriptsPath: /emptydir-volume/scripts
  github:
    endpoint: github-webhook  
    secret: "}VY*IsCn/OX:7R@"
    branch: master
    isScriptInline: false
    commandArg: |-
      #!/bin/bash
      export GITHUB_EVENT=$0 COMMIT_HASH=$1 REPO_HTTPS=$1 REPO_SSH=$2
      kubectl version && helm version
  gitlab:
    endpoint: gitlab-webhook  
    secret: "}VY*IsCn/OX:7R@"
    branch: master
    isScriptInline: true
    commandArg: |-
      export EVENT_TYPE=$0 COMMIT_HASH=$1 HTTP_URL=$2 SSH_URL=$3
      kubectl version && helm version

pipelineJob:
  enabled: true
  clone:
    cloningRepositoryUrl: <URL_FROM_WEBHOOK_PAYLOAD>
    sshSecret: ssh-secret
  build:
    buildToolImage:
      repository: gcr.io/makisu-project/makisu 
      tag: v0.1.11
      pullPolicy: Always
      makisuSecret: docker-registry-config
    targetImage:
      host: gcr.io
      repository: fabijanbajo/fabijanbajo
      tag: <COMMIT_HASH_FROM_WEBHOOK_PAYLOAD>
  deploy:
    helmChart:
      name: fabijanbajo
      namespace: fabijanbajo
      path: kubernetes
