# Default values for k8s-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: gcr.io/fabijanbajo/k8s-webhook
  tag: "0.1.0"
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
  #   certmanager.k8s.io/acme-challenge-type: http01
  # hosts:
  # - host: some.domain.io
  #   paths:
  #   - /hooks/github-webhook
  # tls:
  # - secretName: tls-secret
  #   hosts:
  #   - some.domain.io

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

webhook:
  github:
    endpoint: github-webhook  
    secret: ""
    branch: master
    script: |-
      #!/bin/bash
      kubectl version
      helm version
      # Example @ https://github.com/Bajocode/k8s-webhook

pipelineJob:
  clone:
    cloningRepositoryUrl: <REPOURL_REPLACEME>
    sshSecret: ssh-secret
  build:
    buildToolImage:
      repository: gcr.io/makisu-project/makisu 
      tag: v0.1.11
      pullPolicy: Always
      makisuSecret: docker-registry-config
    targetImage:
      host: gcr.io
      repository: fabijanbajo/fabijanbajo
      tag: <TARGETTAG_REPLACEME>
  deploy:
    helmChart:
      name: chartname
      namespace:
      # Relative path from fetched git repo or hosted chart
      path:
